In [6]:
import numpy as np
import pandas as pd

In [155]:
class Queens():
    def __init__(self, n):
        self.n = n
        self.board = np.array([["*" for _ in range(n)] for _ in range(n)])
        self.state = ["*" for _ in range(n)]
        self.available = np.array([["O" for _ in range(n)] for _ in range(n)])
    
    def print_board(self):
        """
        Print current state of the game.
        """
        return print(pd.DataFrame(self.board))
    
    def print_available(self):
        """
        Prints available places.
        """
        return print(pd.DataFrame(self.available))
    
    def is_sol(self):
        """
        Check if current state is a solution.
        """
        diagonals = [self.board.diagonal(i) for i in range(-self.n+1,self.n)] + \
                    [self.board[::-1,:].diagonal(i) for i in range(-self.n+1,self.n)]
        for d in diagonals:
            if list(d).count("Q") != 1:
                return False
        return True
    
    def put_queen(self,x,y):
        """
        Place a queen
        """
        if self.available[y][x] == "X": return "Not a valid movement. Try again!"
        self.state[x] = y
        self.board[y][x] = "Q"
        self.update_available(x,y)
        return self.print_board()
    
    def update_available(self,x,y):
        self.available[y][x] = "X"
        self.available[y,:] = "X"
        self.available[:,x] = "X"
        
        aux = np.arange(self.n)
        diag_1 = aux[::-1,None] == aux + self.n - y - x -1
        diag_2 = aux[:,None] == aux + y - x
        self.available[diag_1|diag_2] = "X"
    
    def allowed_moves(self):
        """
        Return a list of allowed moves left.
        """
        return list(zip(*np.where(self.available == "O")))
          
    def random_board(self):
        """
        Return a random placement of the queens.
        """
        self.restart()
        self.state = np.random.permutation(self.n)
        for i,s in enumerate(self.state):
            self.board[s][i] = "Q"
        self.available[:,:] = "X"
        return self.print_board()
    
    def restart(self):
        """
        Restart the game.
        """
        self.__init__(self.n)
        

In [156]:
game = Queens(8)

# Environment 
Chess board

In [157]:
game.print_board()

   0  1  2  3  4  5  6  7
0  *  *  *  *  *  *  *  *
1  *  *  *  *  *  *  *  *
2  *  *  *  *  *  *  *  *
3  *  *  *  *  *  *  *  *
4  *  *  *  *  *  *  *  *
5  *  *  *  *  *  *  *  *
6  *  *  *  *  *  *  *  *
7  *  *  *  *  *  *  *  *


# Agent that performs random actions

In [158]:
game.random_board()

   0  1  2  3  4  5  6  7
0  *  Q  *  *  *  *  *  *
1  *  *  *  *  Q  *  *  *
2  *  *  *  *  *  *  *  Q
3  *  *  Q  *  *  *  *  *
4  *  *  *  *  *  Q  *  *
5  *  *  *  Q  *  *  *  *
6  *  *  *  *  *  *  Q  *
7  Q  *  *  *  *  *  *  *


# Agent that learns

In [170]:
game.state

array([7, 0, 3, 5, 1, 4, 6, 2])

In [171]:
game.is_sol()

False

# Other methods

In [160]:
game.print_available()

   0  1  2  3  4  5  6  7
0  X  X  X  X  X  X  X  X
1  X  X  X  X  X  X  X  X
2  X  X  X  X  X  X  X  X
3  X  X  X  X  X  X  X  X
4  X  X  X  X  X  X  X  X
5  X  X  X  X  X  X  X  X
6  X  X  X  X  X  X  X  X
7  X  X  X  X  X  X  X  X


In [161]:
game.put_queen(2,5)

'Not a valid movement. Try again!'

In [162]:
game.state

array([7, 0, 3, 5, 1, 4, 6, 2])

In [163]:
game.print_available()

   0  1  2  3  4  5  6  7
0  X  X  X  X  X  X  X  X
1  X  X  X  X  X  X  X  X
2  X  X  X  X  X  X  X  X
3  X  X  X  X  X  X  X  X
4  X  X  X  X  X  X  X  X
5  X  X  X  X  X  X  X  X
6  X  X  X  X  X  X  X  X
7  X  X  X  X  X  X  X  X


In [166]:
game.allowed_moves()

[]

In [167]:
game.state

array([7, 0, 3, 5, 1, 4, 6, 2])